version: '3.3'
services:
  kong:
    image: kong
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
      KONG_DB_UPDATE_PROPAGATION: 5
    ports:
      - 8000
      - 8443
      - 8001
      - 8444
    depends_on:
      - kong-database
    networks:
      - app-internal-link
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: ${KONG_LIMITS_MEMORY}
  kong-database:
    image: cassandra
    restart: always
    ports:
      - 9042
    volumes:
      - kong-data:/var/lib/cassandra:Z
    networks:
      - app-internal-link
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: ${KONG_DB_LIMITS_MEMORY}
  konga:
    image: pantsel/konga:0.10.2
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 1337
    networks:
      - app-internal-link
    deploy:
      resources:
        limits:
          memory: ${KONGA_LIMITS_MEMORY}
networks:
  app-internal-link:
    external:
      name: app-internal-link
volumes:
  kong-data:
    driver: local
    driver_opts: 
      type: none
      device: ${KONG_CASSANDRA_PATH}
      o: bind
