version: '3.3'
services:
  nginx:
    image: nginx-curl
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - app-internal-link
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: ${NGINX_LIMITS_MEMORY}
networks:
  app-internal-link:
    external:
      name: app-internal-link
